### ISSUE TITLE
Publish to npm repo

### ISSUE THREAD

**Issue by hansmbakker** [ripjar/passport-client-cert#1]
Interesting project!

It would be helpful if you could publish it to the npm repository so that it can be easily installed.

**Comment by joews** [comment]
Hi, thanks for the issue. it's a useful reminder - I have been meaning to do this for some time! I will make a couple of improvements and try to publish this week.

**Comment by joews** [comment]
I have now published - https://www.npmjs.com/package/passport-client-cert

Please note I have renamed the repo to passport-client-cert for clarity.

**Comment by hansmbakker** [comment]
:+1:
