### ISSUE TITLE
Consider using  ssl_client_raw_cert and pkijs

### ISSUE THREAD

**Issue by rmhrisk** [ripjar/passport-client-cert#10]
One shortcoming of Nginx is that it requires that the server use the same list of CAs for CCA as it uses for other parts of operations. This means when using Nginx you typically need to either "open yourself up" to unnecessary trust anchors or disable verification of CCA certificates in Nginx (I think this isnt a problem in Apache but its been a while since I have looked, I am not sure about Node).

For this reason I would recommend designing this so it doesn't rely on the server logic for validation of the cert and instead do your own validation using $ssl_client_raw_cert and https://pkijs.org/examples/X509_cert_complex_example.html

**Comment by joews** [comment]
> For this reason I would recommend designing this so it doesn't rely on the server logic for validation of the cert

Does "validation" here mean checking that the client cert is trusted? Node's `https` module handles that. This module assumes that the certificate is trusted by the platform; userland validation is out of scope here.

**Comment by joews** [comment]
I'm sorry - I misunderstood. That's an interesting point, thanks!

I believe Node has the same shortcoming here; I don't know of a way to restrict a CA to CCA only. In my use case I trust a single in-house CA so I haven't encountered this problem.

This module can also handle userland validation:
1. Disable the Node `https` server's platform validation with [`rejectUnauthorized: false`](https://nodejs.org/api/tls.html#tls_tls_createserver_options_secureconnectionlistener).
2. Perform userland validation by checking [client and issuer certificate details](https://nodejs.org/api/tls.html#tls_tlssocket_getpeercertificate_detailed) in the authorisation callback.

Does that cover the case you discuss?
