### ISSUE TITLE
Matching against a CN alone is insecure

### ISSUE THREAD

**Issue by rmhrisk** [ripjar/passport-client-cert#8]
CNs themselves are not guaranteed to be unique, you can only uniquely identify a certificte with one of these options:
1. subject dn + issuer dn
2. subject dn + aki
3. ski + aki
4. hash of certificate
5. aki + serial

Not all certificates will have subjects (it is standards compliant to have a nul subject), for this reason the only secure and reliable way to do cert to user mapping is 3, 4, 5

This is important for a few reasons, one of the most significant being many CCA deployments will trust more than one CA (on purpose or by accident) for this reason two CAs can issue the same certificate and you would treat them the same.

**Comment by joews** [comment]
Thanks for the feedback!

This module doesn't test client identity itself - that's the module user's responsibility. We pass the [client certificate](https://nodejs.org/api/tls.html#tls_tlssocket_getpeercertificate_detailed) to the [passport auth callback](https://github.com/ripjar/passport-client-cert/blob/c59ae7b986cf29ed2890272dc14e59b616f8ba95/examples/example-server.js#L31) to enable this.

However, we could improve our docs and example by a) matching against more fields and b) linking to a document that explains how to do this securely. Can you recommend an authoritative source?
