### ISSUE TITLE
Will not work when behind Apache or Nginx

### ISSUE THREAD

**Issue by rmhrisk** [ripjar/passport-client-cert#9]
It is common for various reasons to put a web server in front of your node implementation, it seems upon cursory review this presumes node is terminating the connection, you can make this work behind a load balancer by setting some combination of these headers (presuming Nginx) and validating against that:

1: cert hash
                # proxy_set_header X-SSL-Client-hash $ssl_client_fingerprint;

1: cert in pem
                # proxy_set_header X-SSL-Client-hash $ssl_client_raw_cert;

3: issuer dn and subject serial
                # proxy_set_header X-SSL-Issuer $ssl_client_i_dn;
                # proxy_set_header X-SSL-Client-Serial $ssl_client_serial;

4: - issuer and subject dns
                # proxy_set_header X-SSL-Client-S-DN $ssl_client_s_dn;
                # proxy_set_header X-SSL-Client-S-DN $ssl_client_i_dn;

This would scale better than the current approach, you can set session caching very low for the associated vhost, get the server certificate with one of the lets encrypt clients easily and in general it should be able to work smoothly.

Oh, and you also want to be sure to check the value of : $ssl_client_verify

**Comment by joews** [comment]
> this presumes node is terminating the connection

Yes, that's the goal of this module. [passport-trusted-header](https://github.com/ripjar/passport-trusted-header) fulfils the use case you describe.

 Thanks!
